# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Content First Prototyping
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: your-twitter-username
github_username:  your-github-username

exclude: 
    - node_modules
    - bower_components
    - package.json
    - bower.json
    - scss
    - gulpfile.js

keep_files: [css/app.css] # keeps the _site css from being blown away on build (it is being generated by gulp-sass)

# Build settings
markdown: kramdown

# Page Generator settings
page_gen:
  - data: 'catalogue'
    name: 'name'
    template: 'detail'
  - data: 'directory'
    name: 'last-name'
    template: 'detail'
  - data: 'feed'
    name: 'event-name'
    template: 'detail'